export const TRIGGER_ARROW_EDGE_OFFSET = 6
export const TRIGGER_ARROW_EDGE_OFFSET_VERTICAL = 6
export const TRIGGER_ARROW_SIZE = 16
export const TRIGGER_ARROW_HALF_SIZE = TRIGGER_ARROW_SIZE / 2
export const TRIGGER_ARROW_VERTICAL_CENTER_INSET = 6

export const TRIGGER_ARROW_HORIZONTAL_CENTER_OFFSET =
  TRIGGER_ARROW_EDGE_OFFSET + TRIGGER_ARROW_HALF_SIZE
export const TRIGGER_ARROW_VERTICAL_CENTER_OFFSET =
  TRIGGER_ARROW_EDGE_OFFSET_VERTICAL + TRIGGER_ARROW_VERTICAL_CENTER_INSET